### PR TITLE
feat: add github actions for npm publish

### PR DESCRIPTION
**Pull request by aneeshrelan**
Implements #3 

Adding a Github action workflow file to automatically publish to NPM on merges to `master`

- [x]  Setup Github action for NPM deployment

### CODE REVIEW

**Comment by aneeshrelan** [comment]
@karlmarxlopez I'm not really sure how to test this out completely. Although tried out [act](https://github.com/nektos/act) to test it out locally to an extent

**Comment by SpaghettiC0des** [comment]
@aneeshrelan Did it work locally?

**Comment by aneeshrelan** [comment]
Yup, everything seems alright locally!

```
act
[Publish to NPM/npm-publish] 🚀  Start image=node:12.6-buster-slim
[Publish to NPM/npm-publish]   🐳  docker run image=node:12.6-buster-slim entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[Publish to NPM/npm-publish]   🐳  docker cp src=/Users/rajiv/Desktop/open-source/useStateWithLayoutAnimation/. dst=/github/workspace
[Publish to NPM/npm-publish] ⭐  Run Checkout repo
[Publish to NPM/npm-publish]   ✅  Success - Checkout repo
[Publish to NPM/npm-publish] ⭐  Run Set up NodeJS
[Publish to NPM/npm-publish]   ☁  git clone 'https://github.com/actions/setup-node' # ref=v1
[Publish to NPM/npm-publish]   🐳  docker cp src=/Users/rajiv/.cache/act/actions-setup-node@v1 dst=/actions/
[Publish to NPM/npm-publish]   💬  ::debug::isExplicit:
[Publish to NPM/npm-publish]   💬  ::debug::explicit? false
[Publish to NPM/npm-publish]   💬  ::debug::evaluating 0 versions
[Publish to NPM/npm-publish]   💬  ::debug::match not found
[Publish to NPM/npm-publish]   💬  ::debug::evaluating 412 versions
[Publish to NPM/npm-publish]   💬  ::debug::matched: v12.18.4
[Publish to NPM/npm-publish]   💬  ::debug::isExplicit: 12.18.4
[Publish to NPM/npm-publish]   💬  ::debug::explicit? true
[Publish to NPM/npm-publish]   💬  ::debug::checking cache: /opt/hostedtoolcache/node/12.18.4/x64
[Publish to NPM/npm-publish]   💬  ::debug::not found
[Publish to NPM/npm-publish]   💬  ::debug::Downloading https://nodejs.org/dist/v12.18.4/node-v12.18.4-linux-x64.tar.gz
[Publish to NPM/npm-publish]   💬  ::debug::Destination /tmp/523a549e-d4f4-4acb-9a5f-a04d34831849
[Publish to NPM/npm-publish]   💬  ::debug::download complete
[Publish to NPM/npm-publish]   💬  ::debug::Checking tar --version
[Publish to NPM/npm-publish]   💬  ::debug::tar (GNU tar) 1.30%0ACopyright (C) 2017 Free Software Foundation, Inc.%0ALicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.%0AThis is free software: you are free to change and redistribute it.%0AThere is NO WARRANTY, to the extent permitted by law.%0A%0AWritten by John Gilmore and Jay Fenlason.
| [command]/bin/tar xz --warning=no-unknown-keyword -C /tmp/ac586654-8527-44fa-827b-e1e63fdec920 -f /tmp/523a549e-d4f4-4acb-9a5f-a04d34831849
[Publish to NPM/npm-publish]   💬  ::debug::Caching tool node 12.18.4 x64
[Publish to NPM/npm-publish]   💬  ::debug::source dir: /tmp/ac586654-8527-44fa-827b-e1e63fdec920/node-v12.18.4-linux-x64
[Publish to NPM/npm-publish]   💬  ::debug::destination /opt/hostedtoolcache/node/12.18.4/x64
[Publish to NPM/npm-publish]   💬  ::debug::finished caching tool
[Publish to NPM/npm-publish]   ⚙  ::add-path:: /opt/hostedtoolcache/node/12.18.4/x64/bin
| [command]/opt/hostedtoolcache/node/12.18.4/x64/bin/node --version
| v12.18.4
| [command]/opt/hostedtoolcache/node/12.18.4/x64/bin/npm --version
| 6.14.6
[Publish to NPM/npm-publish]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/tsc.json
[Publish to NPM/npm-publish]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/eslint-stylish.json
[Publish to NPM/npm-publish]   ❓  ##[add-matcher]/actions/actions-setup-node@v1/.github/eslint-compact.json
[Publish to NPM/npm-publish]   ✅  Success - Set up NodeJS
[Publish to NPM/npm-publish] ⭐  Run Build package
|
| > yarn@1.22.10 preinstall /opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/yarn
| > :; (node ./preinstall.js > /dev/null 2>&1 || true)
|
| /opt/hostedtoolcache/node/12.18.4/x64/bin/yarn -> /opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/yarn/bin/yarn.js
| /opt/hostedtoolcache/node/12.18.4/x64/bin/yarnpkg -> /opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/yarn/bin/yarn.js
| + yarn@1.22.10
| added 1 package in 1.477s
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 88.03s.
yarn run v1.22.10
$ tsc
Done in 10.51s.
[Publish to NPM/npm-publish]   ✅  Success - Build package
[Publish to NPM/npm-publish] ⭐  Run Publish
[Publish to NPM/npm-publish]   ☁  git clone 'https://github.com/JS-DevTools/npm-publish' # ref=v1
[Publish to NPM/npm-publish]   🐳  docker cp src=/Users/rajiv/.cache/act/JS-DevTools-npm-publish@v1 dst=/actions/
[Publish to NPM/npm-publish]   💬  ::debug::Reading package manifest from /github/workspace/package.json
[Publish to NPM/npm-publish]   💬  ::debug::MANIFEST:%0A{%0A  "name": "use-state-with-layout-animation",%0A  "version": {%0A    "options": {%0A      "loose": false,%0A      "includePrerelease": false%0A    },%0A    "loose": false,%0A    "includePrerelease": false,%0A    "raw": "1.0.6",%0A    "major": 1,%0A    "minor": 0,%0A    "patch": 6,%0A    "prerelease": [],%0A    "build": [],%0A    "version": "1.0.6"%0A  }%0A}
[Publish to NPM/npm-publish]   💬  ::debug::Running command: npm config get userconfig
[Publish to NPM/npm-publish]   💬  ::debug::Reading NPM config from /github/home/.npmrc
[Publish to NPM/npm-publish]   💬  ::debug::OLD NPM CONFIG: <none>
[Publish to NPM/npm-publish]   💬  ::debug::NEW NPM CONFIG: %0A//registry.npmjs.org/:_authToken=${INPUT_TOKEN}%0Aregistry=https://registry.npmjs.org/%0A
[Publish to NPM/npm-publish]   💬  ::debug::Writing new NPM config to /github/home/.npmrc
[Publish to NPM/npm-publish]   💬  ::debug::Running command: npm view use-state-with-layout-animation version
[Publish to NPM/npm-publish]   💬  ::debug::The latest version of use-state-with-layout-animation is at v1.0.6
[Publish to NPM/npm-publish]   💬  ::debug::OUTPUT:%0A{%0A  "package": "use-state-with-layout-animation",%0A  "type": "none",%0A  "version": "1.0.6",%0A  "oldVersion": "1.0.6",%0A  "dryRun": true%0A}
|
| 📦 use-state-with-layout-animation v1.0.6 is already published to NPM
[Publish to NPM/npm-publish]   ⚙  ::set-output:: type=none
[Publish to NPM/npm-publish]   ⚙  ::set-output:: version=1.0.6
[Publish to NPM/npm-publish]   ⚙  ::set-output:: old-version=1.0.6
[Publish to NPM/npm-publish]   ⚙  ::set-output:: dry-run=true
[Publish to NPM/npm-publish]   ✅  Success - Publish
```

I used a `dry-run` to make it run locally

**Comment by aneeshrelan** [comment]
You'll need to make sure the `NPM_AUTH_TOKEN` is added to the repo secrets, which was confirmed to be there

**Comment by SpaghettiC0des** [comment]
@aneeshrelan Thank you! I'll review this tomorrow.

**Comment by aneeshrelan** [comment]
@karlmarxlopez Did you get a chance to review this?

**Comment by SpaghettiC0des** [comment]
@aneeshrelan Yes. LGTM. Merging it now. Thank you!

**Pull request merged**
